codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "80...100"

  ignore:
    - tests/**/*
    - config/**/*
    - mirage/**/*
    - vendor/**/*
    - public/**/*
    - assets/**/*
